### ISSUE TITLE
New REPL: `:new` doesn't reset the save file location to null

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-client-java#14]
cc: @jgkamat 

Just a random thing I noticed while playing out with the new Alda REPL:

If you build a score in the REPL, then enter `:save /tmp/somefile.alda`, it will write the score to that file as expected.

But then, if you enter `:new` followed by more lines of code and then `:save`, it will replace the contents of `/tmp/somefile.alda` with everything you wrote after entering `:new`.

**Comment by jgkamat** [comment]
I'll make a quick patch for this, since it's pretty important (people can overwrite their files accidentally).
