### ISSUE TITLE
REPL: confirm before loading/starting a new score

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-client-java#17]
Moved from https://github.com/alda-lang/alda-core/issues/39.

Quoting @elyisgreat:
> Pretty much the title. If a score is loaded in using :load, it will not throw an override warning if there is already a score in the REPL.

When using the `:new` and `:load` commands, we should check to see if the score in the REPL has any changes compared to the score on disk, and if so, prompt for confirmation.

Maybe we could offer an improvement over the old REPL, and offer a few choices:

- (a)bort (don't load/create new score)
- (s)ave (then load/create new score)
- (d)iscard changes (then load/create new score)

We could also offer these same choices before exiting the REPL, if there are any unsaved changes.

**Comment by elydpg** [comment]
Also, if `:load` is passed a nonexistent file `file`, it simply says `There was an error reading 'file'`, instead of saying no file was found.
