### ISSUE TITLE
REPL: check if server is up when starting

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-client-java#18]
Moved from https://github.com/alda-lang/alda-core/issues/40

Quoting @elyisgreat:
> In 1.0.0rc57, the REPL now requires the server to run, finally uniting the separate interfaces. However, the REPL still opens even if the server is down. Of course, when attempting to do anything without the server, an error is thrown, however it may make more sense to check the server status prior to starting the REPL.

Quoting myself:
> I like this idea. I think maybe what we should do is check to see if the server is up, and if it isn't, ask if you want to start the server, and start it for you.

**Comment by jgkamat** [comment]
Probably dependent on #13, and fairly easy after that.

**Comment by daveyarwood** [comment]
Closed via #20.
