### ISSUE TITLE
`alda update` fails to download file on Windows 10

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-client-java#24]
Moved from https://github.com/alda-lang/alda-core/issues/43.

See that issue for a detailed summary of the problem along with a stacktrace.

I suspect that this is a Windows-specific issue where the OS refuses to let a program replace itself while the program is running.

Unfortunately, I don't have a quick fix for this, as I'm not equipped to troubleshoot Windows-specific issues. Any help from Windows developers would be appreciated.

**Comment by jgkamat** [comment]
I'm no windows developer, but I have a windows box for now so I'll give it a stab.
Is this a new issue, or has this just never worked (I'm not sure we got a confirmation from windows users if this ever worked before).

Right now, running `cmd` without root gives me:
```
Install alda '1.0.0-rc60' over '1.0.0-rc59' ? [yN]: y
Downloading https://github.com/alda-lang/alda/releases/download/1.0.0-rc60/alda.exe...
An error occured while downloading a file (2).
java.io.FileNotFoundException: C:\Program Files (x86)\Alda\alda.exe (Access is denied)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at alda.Util.downloadFile(Util.java:190)
        at alda.AldaClient.updateAlda(AldaClient.java:87)
        at alda.Main.main(Main.java:222)

Updated alda 1.0.0-rc59 => 1.0.0-rc60.
If you have any currently running servers, you may want to restart them so that they are running the latest version.
```
and with root gives me (reported earlier)
```
Install alda '1.0.0-rc60' over '1.0.0-rc59' ? [yN]: y
Downloading https://github.com/alda-lang/alda/releases/download/1.0.0-rc60/alda.exe...
An error occured while downloading a file (2).
java.io.FileNotFoundException: C:\Program Files (x86)\Alda\alda.exe (The process cannot access the file because it is being used by another process)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at alda.Util.downloadFile(Util.java:190)
        at alda.AldaClient.updateAlda(AldaClient.java:87)
        at alda.Main.main(Main.java:222)

Updated alda 1.0.0-rc59 => 1.0.0-rc60.
If you have any currently running servers, you may want to restart them so that they are running the latest version.
```

If you have any ideas, let me know, cause I'm just going to try random things and see what happens... 😢

I suspect we won't be able to get this permission ever on windows (unless this is a new issue)....

**Comment by daveyarwood** [comment]
I have a feeling it's just never worked on Windows 10. Or perhaps it works, but there are some hoops we need to jump through to get the proper permissions to overwrite alda.exe.

**Comment by jgkamat** [comment]
After a little bit of googling, [this SO post](https://stackoverflow.com/questions/9162969/how-can-a-c-binary-replace-itself) seems like the best solution. IE: we would:

Move `alda.exe` -> `alda-old.exe`
Download `alda.exe` from website
If successfull, delete `alda-old.exe`
If not, rename `alda-old.exe` back to `alda.exe`. 

I'll try that out and see if it works. Do you think I should make this a windows-specific hack, or make it do this behavior on all platforms? I'm leaning to all platforms, simply because it will be easier to test (and a more consistent behavior for everyone).

I'm not going to try to write this on windows (because I honestly have no idea how to set that up), so how would I go about building a windows version of `alda.exe`? You answered part of this [here](https://github.com/alda-lang/alda-client-java/pull/20#issuecomment-305976279), but I'm not sure how to tweak it for windows... :/

**Comment by daveyarwood** [comment]
I'd say if this works on Windows and *nix, we should make it the behavior for all platforms so that it's consistent. I can test on OS X, if that helps.

Running the `boot build` task in the alda-lang/alda repo will build both `alda` and `alda.exe`. `launch4j` is required in order to build the Windows executable `alda.exe`. I documented the process here: https://github.com/alda-lang/alda/blob/master/doc/building-the-alda-executable.md

**Comment by jgkamat** [comment]
Hmm, my `boot build` seems to have problems building the exe file (it pops up with a window, and I'm not sure what to put into it), but it builds the linux binary just fine. Do you think you could build the PR I'm about to make for windows so I can test it out (and we'll see if this approach works :P).

Before building, could you also apply [lower-version.txt](https://github.com/alda-lang/alda-client-java/files/1076537/lower-version.txt) so we can test the updater out (just fake the lower version).
