### ISSUE TITLE
Chords shortcuts

### ISSUE THREAD

**Issue by MinaBombo** [alda-lang/alda-client-java#29]
Wouldn't it be useful to add a chords shortcut feature so instead for example writing: c/e-/g the user would be able to write Cm?

**Comment by daveyarwood** [comment]
I like this idea, but I think it's best left as something that can be defined on top of Alda, rather than incorporated into the language itself. You can define your own chord variables in an Alda score like this:

```
Cm = c/e-/g
Fm = c/f/a-
GM = d/g/b

piano: Cm Fm GM Cm
```

**Comment by MinaBombo** [comment]
Agreed, but I also suggest a script file that can be optionally loaded to automatically generates these chords so I don't have to write all of them.
Secondly I suggest the ability control chord duration after deceleration; if I understand well to control chord duration you control the notes duration like this Cm = c2/e-2/g2 what I suggest is being able to do this
Cm = c/e-/g
Cm2 Cm1 
Which will lead to my third suggestion, declaring a variable with relation to another variable, the ability to do this 
Cm = c/e-/g
Fm = c/f/a-
GM = d/g/b
Waltz(CmFmFm) = Cm Fm Fm 
AnotherRhythm(Cm1GM2GM3) = Cm1 GM2 GM3 
And ultimately reaching
Cm = c/e-/g
Fm = c/f/a-
GM = d/g/b
Waltz(v[3]) = v[0] v[1] v[2]
piano Waltz(Cm,Fm,Fm)

**Comment by daveyarwood** [comment]
> Agreed, but I also suggest a script file that can be optionally loaded to automatically generates these chords so I don't have to write all of them.

There are two planned features that I think could make this an easier experience:

- Multiple-file scores (https://github.com/alda-lang/alda-core/issues/8) would allow someone to define a library of chord variables in its own file, and the file could be reused as a component of other scores.

- A plugin system (https://github.com/alda-lang/alda-core/issues/2) would allow one to write an Alda plugin that alters the way some aspect of the parser/score-builder behaves. The Alda client and server would have built-in support for these plugins, which could be hosted e.g. in a GitHub repo and downloaded and used easily by including a line like `plugin daveyarwood/alda-chords 0.1.0` at the top of an Alda score.

---

> Secondly I suggest the ability control chord duration after deceleration; if I understand well to control chord duration you control the notes duration like this Cm = c2/e-2/g2 what I suggest is being able to do this
> Cm = c/e-/g
> Cm2 Cm1

I can see how that would be useful, but unfortunately I don't think we can make variables behave that way in Alda. A variable can contain a sequence of notes that all have different durations, so I don't think it makes sense conceptually for a reference to a variable to have a duration.

---

> Which will lead to my third suggestion, declaring a variable with relation to another variable, the ability to do this
> Cm = c/e-/g
> Fm = c/f/a-
> GM = d/g/b
> Waltz(CmFmFm) = Cm Fm Fm
> AnotherRhythm(Cm1GM2GM3) = Cm1 GM2 GM3
> And ultimately reaching
> Cm = c/e-/g
> Fm = c/f/a-
> GM = d/g/b
> Waltz(v[3]) = v[0] v[1] v[2]
> piano Waltz(Cm,Fm,Fm)

This is a very interesting suggestion -- if I'm understanding correctly, it would be the ability to define and use functions in Alda syntax.

We do already have this feature, technically, although the syntax is not as concise as what you're imagining, and it requires a little knowledge of Clojure. For a little bit of context, see: https://github.com/alda-lang/alda/blob/master/doc/inline-clojure-code.md

You can do something like this:

```clojure
(defn waltz [chord-1 chord-2 chord-3]
  (for [notes [chord-1 chord-2 chord-3]]
    (apply chord (map #(note (pitch %)) notes))))

(def c-major [:c :e :g])
(def f-major [:c :f :a])

piano:
  (waltz c-major f-major f-major) *4
```

There is also the `alda-code` helper function, which allows you to use strings of Alda code within your Clojure code for convenience:

```clojure
(defn waltz [chord-1 chord-2 chord-3]
  (for [string [chord-1 chord-2 chord-3]]
    (alda-code string)))

(def c-minor "c/e-/g")
(def f-minor "c/f/a-")

piano:
  (waltz c-minor f-minor f-minor) *4
```

Working with functions allows you to do things like parameterize the length of the chord like you mentioned:

```clojure
(defn make-note
  [pitch-components & [length]]
  (if length
    (note (apply pitch pitch-components)
          (duration (note-length length)))
    (note (apply pitch pitch-components))))

(defn make-chord
  [notes]
  (fn [& [length]]
    (apply chord (map #(make-note % length) notes))))

(def c-minor (make-chord [[:c] [:e :flat] [:g]]))
(def f-minor (make-chord [[:c] [:f] [:a :flat]]))

piano:
  (c-minor) *4
  (f-minor 1)
  (c-minor 2)
  (c-minor 4)
  (f-minor 8)
```

I realize this is a lot of code for what seems like a simple idea, but with multiple-file scores, we'll be able to keep the lengthy code in separate files (i.e. libraries) and keep our scores clean.
