### ISSUE TITLE
Maybe improve the error message when the wrong server version is runnning

### ISSUE THREAD

**Issue by Emiluren** [alda-lang/alda-client-java#36]
After upgrading from rc81 to rc82 I forgot to restart the server so I got
```
➜  ~ alda repl
 █████╗ ██╗     ██████╗  █████╗
██╔══██╗██║     ██╔══██╗██╔══██╗
███████║██║     ██║  ██║███████║
██╔══██║██║     ██║  ██║██╔══██║
██║  ██║███████╗██████╔╝██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝  ╚═╝

          1.0.0-rc82
         repl session

Type :help for a list of available commands.

> piano: c

The server is down. Start server on port 27713?
(y)es, (n)o, (q)uit

Unable to start server:
alda.error.AlreadyUpException: Server already up.
	at alda.AldaServer.upBg(AldaServer.java:193)
	at alda.repl.AldaRepl.offerToStartServer(AldaRepl.java:198)
	at alda.repl.AldaRepl.run(AldaRepl.java:311)
	at alda.Main.main(Main.java:259)
```

After I did that I realized that the update text warned me about servers that are already running but maybe it could be made more beginner friendly. I don't know if there's any way for the client to know what version of a server is currently running.

**Comment by daveyarwood** [comment]
It doesn't actually matter to the client if the server is running a different version. In most cases, clients and servers will be compatible with each other even if there is a version mismatch, but in some cases that won't be true, so it is a good practice to run `alda downup` after each time you update Alda, so you get a fresh server that's running the same version as your client.

I thought about having the update process automatically restart the server, but I thought that might be too invasive, and there could be a use case for leaving a server running while you update.

Coming back to the issue at hand, I don't think this is related to the versions of the client and server that are running. I think this might be a timing issue between the client and server. Perhaps you ran `alda up` prior to starting the REPL, and then you started the REPL before the server was fully up and it thought the server was still down, but then it finished coming up?

**Comment by Emiluren** [comment]
Hm, no I'm sure I did not run `alda up` before starting the repl but I guess I'll close this since I have no idea what caused it in that case
