### ISSUE TITLE
 java.lang.IllegalArgumentException: localhost:27713

### ISSUE THREAD

**Issue by DepreTux** [alda-lang/alda-client-java#39]
Hi there,

I'm trying to set up alda for the first time on debian 9 amd64.
I get the following:

> $ alda up
> Exception in thread "main" java.lang.IllegalArgumentException: localhost:27713
> 	at zmq.TcpAddress.resolve(TcpAddress.java:97)
> 	at zmq.Address.resolve(Address.java:80)
> 	at zmq.SocketBase.connect(SocketBase.java:466)
> 	at org.zeromq.ZMQ$Socket.connect(ZMQ.java:1264)
> 	at alda.AldaRequest.getSocket(AldaRequest.java:35)
> 	at alda.AldaRequest.rebuildSocket(AldaRequest.java:51)
> 	at alda.AldaRequest.sendRequest(AldaRequest.java:99)
> 	at alda.AldaRequest.send(AldaRequest.java:155)
> 	at alda.AldaServer.ping(AldaServer.java:58)
> 	at alda.AldaServer.checkForConnection(AldaServer.java:64)
> 	at alda.AldaServer.checkForConnection(AldaServer.java:71)
> 	at alda.AldaServer.upBg(AldaServer.java:215)
> 	at alda.Main.main(Main.java:274)
> 

Am I doing something wrong?

Thanks!

**Comment by daveyarwood** [comment]
Interesting... I took a quick look for places in [TcpAddress.resolve](https://github.com/zeromq/jeromq/blob/v0.4.0/src/main/java/zmq/TcpAddress.java) where it throws IllegalArgumentException, but it didn't tell me much. It just looks like it can't resolve localhost:27713 on your machine for some reason.

Some things you can try:

1. Determine if there are any other applications that might be using port 27713. For example, when I do this on my machine, it shows me that I have an Alda server running on port 27713:

    ```
    $ netstat -nalp | grep 27713
    (Not all processes could be identified, non-owned process info
     will not be shown, you would have to be root to see it all.)
    tcp6       0      0 :::27713                :::*                    LISTEN      30285/java      

    $ ps aux | grep 30285
    dave     17724  0.0  0.0  15236   944 pts/13   S+   07:20   0:00 grep --color=auto 30285
    dave     30285  0.0  2.5 4533948 416788 ?      Sl   Jan04   1:06 java -Dclojure.compiler.direct-linking=true -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -Xmx1024m -Xms256m -jar /home/dave/bin/alda --host tcp://localhost --port 27713 --workers 2 --alda-fingerprint server
    ```

2. Check to see if maybe you have some weird configuration where localhost doesn't resolve to 127.0.0.1.

    If you `cat /etc/hosts`, you should see an entry that says `127.0.0.1 localhost`.

    Are you running a proxy or VPN, by chance?

**Comment by DepreTux** [comment]
For some reason, I had the localhost 127.0.0.1 commented at /etc/hosts

Uncommenting it did the trick!

Thanks!

**Comment by daveyarwood** [comment]
OK, great! :)
