### ISSUE TITLE
Java client needs automated tests

### ISSUE THREAD

**Issue by daveyarwood** [alda-lang/alda-client-java#6]
The code in this repo could use some automated tests.

I'm open to suggestions for test frameworks -- there are a lot of options for Java, and I've only ever tried JUnit. Perhaps some more seasoned Java developers can weigh in on which frameworks they like?

I propose that we do integration-style testing. Before running tests, the test runner should confirm that an Alda server is running and has at least one worker available. Then, we can test that commands like `alda parse -c 'harmonica: c/e/g'`, `alda list`, etc. execute successfully and that the output is what we would expect.

**Comment by superseeker13** [comment]
I have forked the repository and will take a look at it.

**Comment by TBuc** [comment]
Hi all, I've already committed a first integration test, built over the test environment provided by @tobiasriedling , for a new feature I wrote, but I'm looking for a way to start and tear down the remote server just once for _all_ the integration tests since it's an extremely high time-consuming task.

I've tried encapsulating my tests in a TestSuite and then leverage its annotations _@ BeforeClass_ and _@ AfterClass_ , with no success: they never got invoked in my Clojure Boot tests - sometimes, randomly, in my Java Maven ones.

I've now successfully set up a [RunListener](http://maven.apache.org/surefire/maven-surefire-plugin/examples/junit.html#Using_Custom_Listeners_and_Reporters) in a Java Maven test project, which seems to work fine. It is managed by the Failsafe plugin, which intercepts a goal from the Surefire plugin, and ensures the environment is prepared before - and teared down after - integration tests are ran. Code follows.

This is the custom RunListener:
```
import org.junit.runner.Description;
import org.junit.runner.Result;
import org.junit.runner.notification.RunListener;

public class TestListener extends RunListener {
	@Override
	public void testRunStarted(Description description) throws Exception {
		// Called before any tests have been run.
		System.err.println(TestListener.class.getName() + ": testRunStarted");
	}
	@Override
	public void testRunFinished(Result result) throws Exception {
		// Called when all tests have finished
		System.err.println(TestListener.class.getName() + ": testRunFinished");
	}
}
```
And this, just FYI, the Maven configuration for binding it to JUnit:
```
<project>
  [...]
  <build>
	  <plugins>
		  <plugin>
		    <groupId>org.apache.maven.plugins</groupId>
		    <artifactId>maven-surefire-plugin</artifactId>
		    <configuration>
		      <properties>
		        <property>
		          <name>listener</name>
		          <value>org.bucciol.junittest.TestListener</value>
		        </property>
		      </properties>
		    </configuration>
		  </plugin>
	  </plugins>
  </build>
</project>
```
 This the result of executing:

> mvn test

```
[...]
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
org.bucciol.junittest.TestListener: testRunStarted
Running org.bucciol.junittest.AppTest
org.bucciol.junittest.AppTest BeforeClass
org.bucciol.junittest.AppTest Before
org.bucciol.junittest.AppTest Test
org.bucciol.junittest.AppTest After
org.bucciol.junittest.AppTest AfterClass
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.036 sec - in org.bucciol.junittest.AppTest
org.bucciol.junittest.TestListener: testRunFinished
[...]
```


I'd love to port this behavior to this, Boot-managed, project: but I'm new to Cloj and Boot and couldn't sort this out.
**Is there someone who can configure Boot for saying JUnit to make use of a custom RunListener?**
@superseeker13 maybe your have already defined a framework?

**Comment by daveyarwood** [comment]
I read up on this a bit, and it looks like there is [an open PR for cljunit](https://github.com/RadicalZephyr/cljunit/pull/6), the underlying library that is used when we run the JUnit tests via Boot. The PR adds the ability to specify additional RunListeners when running JUnit tests via [boot-junit](https://github.com/RadicalZephyr/boot-junit), the Boot task we're using.

I've left a comment on that PR to see if maybe we can push towards getting this functionality implemented upstream in boot-junit. I think that if that happened, we could implement a RunListener in Java (with code that looks a lot like what @TBuc just posted) that does all of our pre-suite and post-suite setup and teardown, and then simply include the name of our class as a `:listeners` task option in our build.boot where we call the `junit` task.

I also had a thought -- maybe it would be acceptable for us to do all of our setup and teardown in the build.boot before and after we call the `junit` task? I could write some Clojure code in the build.boot that starts a server using the latest `alda/server-clj` artifact, runs the tests the way we're currently doing, and then stops the server afterwards. This would decouple the test setup from the tests themselves, which may or may not be desirable, so I'd like to get some opinions on this before I potentially take a stab at it. @jgkamat @superseeker13 @TBuc @tobiasriedling Thoughts?

**Comment by jgkamat** [comment]
Hmm, I have mixed opinions on this (from what I understand of it at least). On one hand, doing this would make it easier to have the server up running for more testing categories in the future (for example, if we had independent unit/ntegration test tasks, this would avoid starting and stopping the server twice). On the other, it seems a little magical when viewed from the tests alone, and might be a bit more work to maintain. 

Thinking about it, the server takes a really long time to start up, so I like the boot clj code idea slightly more, even though I think the listeners are cleaner overall. I think that for now at least, the easier method is probably what we should go for. I hope the PR gets merged though, so we can consider both options :P

**Comment by daveyarwood** [comment]
The PR got merged, and there is already a new release of boot-junit that uses it!

So, from here, my understanding is that we might be able to get this working if we:

1. Implement a class that extends RunListener.
2. Bump [our boot-junit dependency](https://github.com/alda-lang/alda-client-java/blob/58514a0baca69b15d9d586c1e0a744ed0e5b59f4/build.boot#L6) version to `0.4.0`.
3. Include a `:listeners` task option to [the place where we call the `junit` task](https://github.com/alda-lang/alda-client-java/blob/58514a0baca69b15d9d586c1e0a744ed0e5b59f4/build.boot#L55). I believe this will work:

    ```clojure
    (junit :listeners #{"alda.integrationtests.TheNameOfTheClassThatExtendsRunListener"})
    ```

**Comment by TBuc** [comment]
@daveyarwood, @jgkamat LGTM!

I've implemented the suggested steps on my clone of the project ([see code](https://github.com/alda-lang/alda-client-java/compare/master...TBuc:junitRunListener)), but I'm getting this error:

> $ boot test

```
Compiling 48 Java source files...
Could not load class: java.alda.integrationtests.commands.utils.ReplCommandExecutorWithExpBackoff...
                              java.lang.Thread.run              Thread.java:  748
java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  624
 java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1149
               java.util.concurrent.FutureTask.run          FutureTask.java:  266
                                               ...                               
               clojure.core/binding-conveyor-fn/fn                 core.clj: 1938
                                 boot.core/boot/fn                 core.clj: 1031
                               boot.core/run-tasks                 core.clj: 1021
                    boot.task.built-in/fn/fn/fn/fn             built_in.clj:  804
         radicalzephyr.boot-junit/eval286/fn/fn/fn           boot_junit.clj:   60
                              clojure.core/ex-info                 core.clj: 4617
clojure.lang.ExceptionInfo: Some tests failed or errored
clojure.lang.ExceptionInfo: Some tests failed or errored
    line: 100
```
I've tried some tricks in boot.config but none worked.
Any ideas?

**Comment by daveyarwood** [comment]
Hmm, this is a bit puzzling... it seems like ReplCommandExecutorWithExpBackoff isn't being found on the classpath for some reason. My first thought was that maybe you misspelled part of it? (it is a very long class name, after all -- easy to make mistakes when you're dealing with those!) But it doesn't look misspelled in the place where you imported it, at least as far as I can tell.

Just for the sake of experimentation: does it work if you comment out that import?

**Comment by TBuc** [comment]
I've tried switching the current release of alda-client-java to boot-junit 0.4.0, and it won't work.
I've [raised an issue ](https://github.com/RadicalZephyr/boot-junit/issues/8) in boot-junit project.

**Comment by daveyarwood** [comment]
Aha -- looks like the fix is to change our `:source-paths` in build.boot to:

```clojure
  :source-paths #{"src" "test/java"}
```

Either that or move all the tests up a level from `test/java` so that they're just in the `test` directory.

I'm not sure which is a better fix at this point, as I haven't done enough Java development to know which organization scheme is more idiomatic.

**Comment by RadicalZephyr** [comment]
The truly idiomatic way to lay out a Java project would be to have `src/main/java` contain the java source files, and `src/test/java` contain the tests.  All the standard Java build tools (Ant, Maven, Gradle) tend to expect that to be the layout.  However, a boot project uses a structure more like what you are currently using, with separate `src` and `test` directories.e

Personally, I would drop the `java` directory unless you intend to add another language to the project.  But that's easy enough to add if and when it becomes necessary to add a new language.

**Comment by TBuc** [comment]
#34 moved /test/java/alda/ to /test/alda/

**Comment by daveyarwood** [comment]
I'm going to close this issue at this point. Given the progress being made on Alda v2, I don't think it would be worthwhile to invest a lot of time into writing these types of tests for Alda v1.
